[package]
name = "video-upsampler-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-next = "7.0.1"
image = "0.25.1"
log = "0.4.14"
colored = "2.0.0"
env_logger = "0.11.3"
